// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OeeSystem.Data;

#nullable disable

namespace OeeSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("produksi")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OeeSystem.Models.DowntimeEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLineStop")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNoLoading")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRestBreak")
                        .HasColumnType("bit");

                    b.Property<int>("JobRunId")
                        .HasColumnType("int");

                    b.Property<int>("ReasonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("ReasonId");

                    b.ToTable("tb_lwpmixing_DowntimeEvents", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.DowntimeReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPlanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_DowntimeReasons", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.JobRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DandoriDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DandoriEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastStatusChangeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("ManPowerId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int?>("ScannedJmlKomponen")
                        .HasColumnType("int");

                    b.Property<int?>("ScannedKomponenId")
                        .HasColumnType("int");

                    b.Property<string>("ScannedLotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ScannedPartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ManPowerId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("tb_lwpmixing_JobRuns", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.Komponen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JmlKomponen")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_Komponens", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.Machine", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InstallationYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("LineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ManufacturingYear")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("tb_lwpmixing_Machines", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.MachineDowntimeReason", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("DowntimeReasonId")
                        .HasColumnType("int");

                    b.HasKey("MachineId", "DowntimeReasonId");

                    b.HasIndex("DowntimeReasonId");

                    b.ToTable("tb_lwpmixing_MachineDowntimeReasons", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.ManPower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_ManPowers", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.NgType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_NgTypes", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_Plants", "produksi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PLT01",
                            Name = "Plant Dummy"
                        });
                });

            modelBuilder.Entity("OeeSystem.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("SLOC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StandarCycleTime")
                        .HasColumnType("float");

                    b.Property<string>("UoM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("tb_lwpmixing_Products", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.ProductMachine", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("MachineId")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("ProductId", "MachineId");

                    b.HasIndex("MachineId");

                    b.ToTable("tb_lwpmixing_ProductMachines", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.ProductNgType", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("NgTypeId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "NgTypeId");

                    b.HasIndex("NgTypeId");

                    b.ToTable("tb_lwpmixing_ProductNgTypes", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.ProductionCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BeratAct")
                        .HasColumnType("float");

                    b.Property<int?>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int?>("DurasiProduksiSeconds")
                        .HasColumnType("int");

                    b.Property<int>("GoodCount")
                        .HasColumnType("int");

                    b.Property<string>("InjectionGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("JobRunId")
                        .HasColumnType("int");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotBo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManPowerId")
                        .HasColumnType("int");

                    b.Property<string>("NamaCompound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NgTypeId")
                        .HasColumnType("int");

                    b.Property<string>("NomorLot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penipisan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RejectCount")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("JobRunId");

                    b.HasIndex("ManPowerId");

                    b.HasIndex("NgTypeId");

                    b.ToTable("tb_lwpmixing_ProductionCounts", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.Scw4MType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_Scw4MTypes", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.ScwEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Jenis4MId")
                        .HasColumnType("int");

                    b.Property<int>("JenisRemarkId")
                        .HasColumnType("int");

                    b.Property<int>("JobRunId")
                        .HasColumnType("int");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Jenis4MId");

                    b.HasIndex("JenisRemarkId");

                    b.HasIndex("JobRunId");

                    b.HasIndex("MachineId");

                    b.ToTable("tb_lwpmixing_ScwEvents", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.ScwRemark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("Scw4MTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Scw4MTypeId");

                    b.ToTable("tb_lwpmixing_ScwRemarks", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_Shifts", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_lwpmixing_Users", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShiftId");

                    b.ToTable("tb_lwpmixing_WorkOrders", "produksi");
                });

            modelBuilder.Entity("OeeSystem.Models.DowntimeEvent", b =>
                {
                    b.HasOne("OeeSystem.Models.JobRun", "JobRun")
                        .WithMany("DowntimeEvents")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.DowntimeReason", "Reason")
                        .WithMany("DowntimeEvents")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRun");

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("OeeSystem.Models.JobRun", b =>
                {
                    b.HasOne("OeeSystem.Models.Machine", "Machine")
                        .WithMany("JobRuns")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.ManPower", "ManPower")
                        .WithMany()
                        .HasForeignKey("ManPowerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OeeSystem.Models.User", "Operator")
                        .WithMany("JobRuns")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.WorkOrder", "WorkOrder")
                        .WithMany("JobRuns")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("ManPower");

                    b.Navigation("Operator");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("OeeSystem.Models.Machine", b =>
                {
                    b.HasOne("OeeSystem.Models.Plant", "Plant")
                        .WithMany("Machines")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OeeSystem.Models.MachineDowntimeReason", b =>
                {
                    b.HasOne("OeeSystem.Models.DowntimeReason", "DowntimeReason")
                        .WithMany("MachineDowntimeReasons")
                        .HasForeignKey("DowntimeReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.Machine", "Machine")
                        .WithMany("MachineDowntimeReasons")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DowntimeReason");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("OeeSystem.Models.Product", b =>
                {
                    b.HasOne("OeeSystem.Models.Plant", "Plant")
                        .WithMany("Products")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OeeSystem.Models.ProductMachine", b =>
                {
                    b.HasOne("OeeSystem.Models.Machine", "Machine")
                        .WithMany("ProductMachines")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.Product", "Product")
                        .WithMany("ProductMachines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OeeSystem.Models.ProductNgType", b =>
                {
                    b.HasOne("OeeSystem.Models.NgType", "NgType")
                        .WithMany("ProductNgTypes")
                        .HasForeignKey("NgTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.Product", "Product")
                        .WithMany("ProductNgTypes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NgType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OeeSystem.Models.ProductionCount", b =>
                {
                    b.HasOne("OeeSystem.Models.Komponen", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId");

                    b.HasOne("OeeSystem.Models.JobRun", "JobRun")
                        .WithMany("ProductionCounts")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.ManPower", "ManPower")
                        .WithMany()
                        .HasForeignKey("ManPowerId");

                    b.HasOne("OeeSystem.Models.NgType", "NgType")
                        .WithMany()
                        .HasForeignKey("NgTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Component");

                    b.Navigation("JobRun");

                    b.Navigation("ManPower");

                    b.Navigation("NgType");
                });

            modelBuilder.Entity("OeeSystem.Models.ScwEvent", b =>
                {
                    b.HasOne("OeeSystem.Models.Scw4MType", "Scw4MType")
                        .WithMany()
                        .HasForeignKey("Jenis4MId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.ScwRemark", "ScwRemark")
                        .WithMany("ScwEvents")
                        .HasForeignKey("JenisRemarkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.JobRun", "JobRun")
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRun");

                    b.Navigation("Machine");

                    b.Navigation("Scw4MType");

                    b.Navigation("ScwRemark");
                });

            modelBuilder.Entity("OeeSystem.Models.ScwRemark", b =>
                {
                    b.HasOne("OeeSystem.Models.Scw4MType", "Scw4MType")
                        .WithMany("Remarks")
                        .HasForeignKey("Scw4MTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scw4MType");
                });

            modelBuilder.Entity("OeeSystem.Models.WorkOrder", b =>
                {
                    b.HasOne("OeeSystem.Models.Product", "Product")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OeeSystem.Models.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.Navigation("Product");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("OeeSystem.Models.DowntimeReason", b =>
                {
                    b.Navigation("DowntimeEvents");

                    b.Navigation("MachineDowntimeReasons");
                });

            modelBuilder.Entity("OeeSystem.Models.JobRun", b =>
                {
                    b.Navigation("DowntimeEvents");

                    b.Navigation("ProductionCounts");
                });

            modelBuilder.Entity("OeeSystem.Models.Machine", b =>
                {
                    b.Navigation("JobRuns");

                    b.Navigation("MachineDowntimeReasons");

                    b.Navigation("ProductMachines");
                });

            modelBuilder.Entity("OeeSystem.Models.NgType", b =>
                {
                    b.Navigation("ProductNgTypes");
                });

            modelBuilder.Entity("OeeSystem.Models.Plant", b =>
                {
                    b.Navigation("Machines");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("OeeSystem.Models.Product", b =>
                {
                    b.Navigation("ProductMachines");

                    b.Navigation("ProductNgTypes");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("OeeSystem.Models.Scw4MType", b =>
                {
                    b.Navigation("Remarks");
                });

            modelBuilder.Entity("OeeSystem.Models.ScwRemark", b =>
                {
                    b.Navigation("ScwEvents");
                });

            modelBuilder.Entity("OeeSystem.Models.User", b =>
                {
                    b.Navigation("JobRuns");
                });

            modelBuilder.Entity("OeeSystem.Models.WorkOrder", b =>
                {
                    b.Navigation("JobRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
